<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <Version>1.30</Version>
    <AssemblyVersion>1.30</AssemblyVersion>
    <FileVersion>1.30</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BenchmarkSuite1" />
    <InternalsVisibleTo Include="NRKLastNed" />
    <InternalsVisibleTo Include="NRKLastNed.Mac" />
  </ItemGroup>

</Project>
